apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tallermgf-ingress
  namespace: tallermgf
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: tallermgf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tallermgf-svc
            port:
              number: 80
