apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: tallermgf    # ðŸ‘ˆ aÃ±ade esto
  labels:
    app: tallermgf
spec:
  selector:
    app: tallermgf
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
